export const SET_PATIENT_PHOTOS = "SET_PATIENT_PHOTOS";
export const SET_LOADING = "SET_LOADING";

export const GET_PATIENT_PHOTOS = 'GET_PATIENT_PHOTOS';
export const GET_PATIENT_PHOTOS_SUCCESS = 'GET_MEDICAL_HISTORIES_SUCCESS';
export const GET_PATIENT_PHOTOS_FAILURE = 'GET_PATIENT_PHOTOS_FAILURE';

export const GET_MEDICAL_HISTORY_REQUEST = 'GET_MEDICAL_HISTORY_REQUEST';
export const GET_MEDICAL_HISTORY_SUCCESS = 'GET_MEDICAL_HISTORY_SUCCESS';
export const GET_MEDICAL_HISTORY_FAILURE = 'GET_MEDICAL_HISTORY_FAILURE';

export const CREATE_MEDICAL_HISTORY_REQUEST = 'CREATE_MEDICAL_HISTORY_REQUEST';
export const CREATE_MEDICAL_HISTORY_SUCCESS = 'CREATE_MEDICAL_HISTORY_SUCCESS';
export const CREATE_MEDICAL_HISTORY_FAILURE = 'CREATE_MEDICAL_HISTORY_FAILURE';

export const UPDATE_MEDICAL_HISTORY_REQUEST = 'UPDATE_MEDICAL_HISTORY_REQUEST';
export const UPDATE_MEDICAL_HISTORY_SUCCESS = 'UPDATE_MEDICAL_HISTORY_SUCCESS';
export const UPDATE_MEDICAL_HISTORY_FAILURE = 'UPDATE_MEDICAL_HISTORY_FAILURE';

export const DELETE_MEDICAL_HISTORY_REQUEST = 'DELETE_MEDICAL_HISTORY_REQUEST';
export const DELETE_MEDICAL_HISTORY_SUCCESS = 'DELETE_MEDICAL_HISTORY_SUCCESS';
export const DELETE_MEDICAL_HISTORY_FAILURE = 'DELETE_MEDICAL_HISTORY_FAILURE';
