export const SET_MEDICAL_HISTORIES = "SET_MEDICAL_HISTORIES";
export const SET_LOADING = "SET_LOADING";

export const GET_MEDICAL_HISTORIES_REQUEST = 'GET_MEDICAL_HISTORIES_REQUEST';
export const GET_MEDICAL_HISTORIES_SUCCESS = 'GET_MEDICAL_HISTORIES_SUCCESS';
export const GET_MEDICAL_HISTORIES_FAILURE = 'GET_MEDICAL_HISTORIES_FAILURE';

export const GET_MEDICAL_HISTORY_REQUEST = 'GET_MEDICAL_HISTORY_REQUEST';
export const GET_MEDICAL_HISTORY_SUCCESS = 'GET_MEDICAL_HISTORY_SUCCESS';
export const GET_MEDICAL_HISTORY_FAILURE = 'GET_MEDICAL_HISTORY_FAILURE';

export const CREATE_MEDICAL_HISTORY_REQUEST = 'CREATE_MEDICAL_HISTORY_REQUEST';
export const CREATE_MEDICAL_HISTORY_SUCCESS = 'CREATE_MEDICAL_HISTORY_SUCCESS';
export const CREATE_MEDICAL_HISTORY_FAILURE = 'CREATE_MEDICAL_HISTORY_FAILURE';

export const UPDATE_MEDICAL_HISTORY_REQUEST = 'UPDATE_MEDICAL_HISTORY_REQUEST';
export const UPDATE_MEDICAL_HISTORY_SUCCESS = 'UPDATE_MEDICAL_HISTORY_SUCCESS';
export const UPDATE_MEDICAL_HISTORY_FAILURE = 'UPDATE_MEDICAL_HISTORY_FAILURE';

export const DELETE_MEDICAL_HISTORY_REQUEST = 'DELETE_MEDICAL_HISTORY_REQUEST';
export const DELETE_MEDICAL_HISTORY_SUCCESS = 'DELETE_MEDICAL_HISTORY_SUCCESS';
export const DELETE_MEDICAL_HISTORY_FAILURE = 'DELETE_MEDICAL_HISTORY_FAILURE';
